## @section Kubernetes settings
##
image:
  ## @param image.registry plex image registry
  ##
  registry: docker.io
  ## @param image.repository plex image repository
  ##
  repository: digrouz/plexmediaserver
  ##
  ## @param image.tag plex image tag
  ## Ref: https://hub.docker.com/r/digrouz/plexmediaserver/tags
  ##
  tag: "latest"
  ## @param image.pullPolicy plex image pull policy
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
## @param fullnameOverride String to override the application name.
##
fullnameOverride: ""
## @section Service Configuration
##
service:
  ## @param service.uid user id running plex
  ##
  uid: 12345
  ## @param service.gid group id running plex
  ##
  gid: 12345
  ## @param service.autoupgrade apply OS updates inside container at startup
  ##
  autoupgrade: 0
  ## @param service.tz Time Zone
  ##
  tz: Europe/Brussels
ingress:
  ## @param ingress.ingressClassName Ingress class name for the Plex Web ingresses
  ##
  ingressClassName: traefik
  webui:
    ## @param ingress.webui.enabled Enable ingress for the Plex Web UI
    ##
    enabled: true
    ## @param ingress.webui.host Host for the Plex Web UI ingress
    ##
    host: ""
    ## @param ingress.webui.tls Enable TLS for the Plex Web UI ingress
    ##
    tls: true
    ## @param ingress.webui.annotations Annotations for the Plex Web UI ingress
    ##
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: []
      cert-manager.io/cluster-issuer: letsencrypt-prod
  plex32469:
    ## @param ingress.plex32469.traefik.entrypoint Traefik entrypoint for Plex 32469 ingress route
    ##
    traefik:
      entrypoint: plex-32469
    ## @param ingress.plex32469.priority Priority for Plex 32469 ingress route
    ##
    priority: 10
  plex8324:
    ## @param ingress.plex8324.traefik.entrypoint Traefik entrypoint for Plex 8324 ingress route
    ##
    traefik:
      entrypoint: plex-8324
    ## @param ingress.plex8324.priority Priority for Plex 8324 ingress route
    ##
    priority: 10
  plex3005:
    ## @param ingress.plex3005.traefik.entrypoint Traefik entrypoint for Plex 3005 ingress route
    ##
    traefik:
      entrypoint: plex-3005
    ## @param ingress.plex3005.priority Priority for Plex 3005 ingress route
    ##
    priority: 10
  plex1900:
    ## @param ingress.plex1900.traefik.entrypoint Traefik entrypoint for Plex 1900 ingress route
    ##
    traefik:
      entrypoint: plex-1900
    ## @param ingress.plex1900.priority Priority for Plex 1900 ingress route
    ##
    weight: 10
  plex5353:
    ## @param ingress.plex5353.traefik.entrypoint Traefik entrypoint for Plex 5353 ingress route
    ##
    traefik:
      entrypoint: plex-5353
    ## @param ingress.plex5353.priority Priority for Plex 5353 ingress route
    ##
    weight: 10
  plex32410:
    ## @param ingress.plex32410.traefik.entrypoint Traefik entrypoint for Plex 32410 ingress route
    ##
    traefik:
      entrypoint: plex-32410
    ## @param ingress.plex32410.priority Priority for Plex 32410 ingress route
    ##
    weight: 10
  plex32411:
    ## @param ingress.plex32411.traefik.entrypoint Traefik entrypoint for Plex 32411 ingress route
    ##
    traefik:
      entrypoint: plex-32411
    ## @param ingress.plex32411.priority Priority for Plex 32411 ingress route
    ##
    weight: 10
  plex32412:
    ## @param ingress.plex32412.traefik.entrypoint Traefik entrypoint for Plex 32412 ingress route
    ##
    traefik:
      entrypoint: plex-32412
    ## @param ingress.plex32412.priority Priority for Plex 32412 ingress route
    ##
    weight: 10
  plex32413:
    ## @param ingress.plex32413.traefik.entrypoint Traefik entrypoint for Plex 32413 ingress route
    ##
    traefik:
      entrypoint: plex-32413
    ## @param ingress.plex32413.priority Priority for Plex 32413 ingress route
    ##
    weight: 10
  plex32414:
    ## @param ingress.plex32414.traefik.entrypoint Traefik entrypoint for Plex 32414 ingress route
    ##
    traefik:
      entrypoint: plex-32414
    ## @param ingress.plex32414.priority Priority for Plex 32414 ingress route
    ##
    weight: 10
## @section Storage persistence Configuration
##
persistence:
  library:
    ## @param persistence.library.type Type of persistence for Plex library
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for Plex library using a persistent volume claim
    ##
    pvc:
      ## @param persistence.library.pvc.storageClass Storage class for Plex library
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.library.pvc.existingClaim Existing persistent volume claim for Plex library
      ## If set, the library will be stored in the existing persistent volume claim
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.library.pvc.size Size of the persistent volume for Plex library
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for Plex library using NFS
    ##      
    nfs:
      ## @param persistence.library.nfs.server NFS server for Plex library
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.library.nfs.path NFS path for Plex library
      ## If not set, the default NFS path will be used
      ##
      path: ""
## @section Extra volumes and mounts
##
## @param extraVolumes Extra volumes to append to the pod's spec.volumes list.
## Supports hostPath, pvc, nfs, configMap and secret volume sources.
## Example:
## extraVolumes:
##   - name: media
##     hostPath:
##       path: /mnt/media
##       type: Directory
extraVolumes: []

## @param extraVolumeMounts Extra mounts to append to the container's volumeMounts list.
## Example:
## extraVolumeMounts:
##   - name: media
##     mountPath: /media
##     readOnly: true
extraVolumeMounts: []

extraObjects: []

