---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-plexmediaserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plexmediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: plexmediaserver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plexmediaserver
    spec:
      containers:
        - name: plexmediaserver
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 32400
              name: plex-http
              protocol: TCP
            - containerPort: 3005
              name: plex-3005
              protocol: TCP
            - containerPort: 8324
              name: plex-8324
              protocol: TCP
            - containerPort: 32469
              name: plex-32469
              protocol: TCP
            - containerPort: 1900
              name: plex-1900
              protocol: UDP
            - containerPort: 5353
              name: plex-5353
              protocol: UDP
            - containerPort: 32410
              name: plex-32410
              protocol: UDP
            - containerPort: 32412
              name: plex-32412
              protocol: UDP
            - containerPort: 32413
              name: plex-32413
              protocol: UDP
            - containerPort: 32414
              name: plex-32414
              protocol: UDP
          volumeMounts:
            - mountPath: /var/lib/plexmediaserver/Library
              name: plex-library
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
      volumes:
        - name: plex-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
