---
{{- if .Values.ingress.webui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plexmediaserver
  {{- if .Values.ingress.webui.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.webui.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.webui.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              name: webui
  {{- if .Values.ingress.webui.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.webui.host }}
      secretName: {{ .Values.ingress.webui.host }}-tls
  {{- end }}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-plex-32469
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.ingressClassName }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32469.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.plex32469.priority }}
    services:
    - name: {{ .Release.Name }}-svc
      port:  32469
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-plex-8324
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.ingressClassName }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex8324.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.plex8324.priority }}
    services:
    - name: {{ .Release.Name }}-svc
      port:  8324
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-plex-3005
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.ingressClassName }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex3005.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.plex3005.priority }}
    services:
    - name: {{ .Release.Name }}-svc
      port:  3005
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-1900
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex1900.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  1900
      weight: {{ .Values.ingress.plex1900.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-5353
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex5353.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  5353
      weight: {{ .Values.ingress.plex5353.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-32410
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32410.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  32410
      weight: {{ .Values.ingress.plex32410.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-32411
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32411.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  32411
      weight: {{ .Values.ingress.plex32411.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-32412
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32412.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  32412
      weight: {{ .Values.ingress.plex32412.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-32413
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32413.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  32413
      weight: {{ .Values.ingress.plex32413.weight }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-plex-32414
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.plex32414.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  32414
      weight: {{ .Values.ingress.plex32414.weight }}