---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plexmediaserver
spec:
  ports:
  - port: 32400
    name: webui
    protocol: TCP
  - port: 1900
    name: dlna
    protocol: UDP
  - port: 5353
    name: bonjour
    protocol: UDP
  - port: 3005
    name: plex-3005
    protocol: TCP
  - port: 8324
    name: plex-8324
    protocol: TCP
  - port: 32469
    name: plex-32469
    protocol: TCP
  - port: 32410
    name: plex-32410
    protocol: UDP
  - port: 32411
    name: plex-32411
    protocol: UDP
  - port: 32412
    name: plex-32412
    protocol: UDP
  - port: 32413
    name: plex-32413
    protocol: UDP
  - port: 32414
    name: plex-32414
    protocol: UDP
  selector:
    app.kubernetes.io/component: plexmediaserver
---
{{- if eq .Values.service.loadBalancer.enabled "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lba-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plexmediaserver
  annotations:
    metallb.io/ip-allocated-from-pool: {{ .Values.service.loadBalancer.ipAddressPool }}
spec:
  selector:
    app.kubernetes.io/component: plexmediaserver
  ports:
    - name: webui
      protocol: TCP
      port: 32400
      targetPort: 32400
    - name: dlna
      protocol: UDP
      port: 1900
      targetPort: 1900
    - name: bonjour
      protocol: UDP
      port: 5353
      targetPort: 5353
    - name: plex-3005
      protocol: TCP
      port: 3005
      targetPort: 3005
    - name: plex-8324
      protocol: TCP
      port: 8324
      targetPort: 8324
    - name: plex-32469
      protocol: TCP
      port: 32469
      targetPort: 32469
    - name: plex-32410
      protocol: UDP
      port: 32410
      targetPort: 32410
    - name: plex-32411
      protocol: UDP
      port: 32411
      targetPort: 32411
    - name: plex-32412
      protocol: UDP
      port: 32412
      targetPort: 32412
    - name: plex-32413
      protocol: UDP
      port: 32413
      targetPort: 32413
    - name: plex-32414
      protocol: UDP
      port: 32414
      targetPort: 32414
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancer.ipAddress }}
{{- end }}
